---
name: "Build and Test Toolchain"
description: "Setup a configurable Rust toolchain for build and test jobs and set that toolchain as the default"

inputs:
  toolchain:
    description: "Rustup toolchain"
    required: true
    default: "stable"
  target:
    description: "Target triple"
    required: false
    default: ""
  override-dir:
    description: "Directory to set the rustup override for"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        rustup toolchain install "$TOOLCHAIN" --profile minimal

    - name: Update toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        rustup update "$TOOLCHAIN"

    - name: Install additional target
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      if: inputs.target != ''
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
        TARGET: ${{ inputs.target }}
      run: |
        rustup target add --toolchain "$TOOLCHAIN" "$TARGET"

    - name: Set default toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        # https://rust-lang.github.io/rustup/overrides.html
        rustup override set "$TOOLCHAIN"

    - name: Show rustup version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        rustup -Vv

    - name: Show rustc version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        rustc +"$TOOLCHAIN" -Vv

    - name: Show cargo version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        cargo +"$TOOLCHAIN" version --verbose

    - name: Check if Cargo.lock is present
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      id: lockfile
      run: |
        if [[ -f Cargo.lock ]]; then
          echo "present=true" >> "$GITHUB_OUTPUT"
        else
          echo "present=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup Rust caching
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      if: steps.lockfile.outputs.present == 'true'
