---
name: "Code Coverage Toolchain"
description: "Setup a nightly Rust toolchain with llvm-tools so code coverage works"

inputs:
  toolchain:
    description: "Rustup toolchain"
    required: true
    default: "nightly"
  override-dir:
    description: "Directory to set the rustup override for"
    required: false
    default: "."

runs:
  using: "composite"
  env:
    TOOLCHAIN: ${{ inputs.toolchain }}
  steps:
    - name: Install toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        rustup toolchain install "$TOOLCHAIN" --profile minimal --component clippy --component rustfmt

    - name: Update toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        rustup update "$TOOLCHAIN"

    - name: Set default toolchain
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        # https://rust-lang.github.io/rustup/overrides.html
        rustup override set "$TOOLCHAIN"

    - name: Show rustup version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        rustup -Vv

    - name: Show rustc version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        rustc +"$TOOLCHAIN" -Vv

    - name: Show cargo version
      shell: bash
      working-directory: ${{ inputs.override-dir }}
      run: |
        cargo +"$TOOLCHAIN" version --verbose
